# Generated by Django 4.2.5 on 2023-09-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_material_nombrematerial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='mobreColor',
            new_name='nombreColor',
        ),
    ]
