# Generated by Django 4.2.5 on 2023-11-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_producto_nombre_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='name',
            field=models.CharField(default=0.00012357884330202668, max_length=255, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.FloatField(default=0.00031456432840515884, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='color',
            name='nombreColor',
            field=models.CharField(max_length=100, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombreMaterial',
            field=models.CharField(max_length=100, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.categoria', verbose_name='Categória'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.talla', verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='talla',
            name='nombreTalla',
            field=models.CharField(max_length=100, verbose_name='Talla'),
        ),
    ]
