# Generated by Django 4.2.5 on 2023-11-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_rename_imagen_producto_image_remove_producto_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='dni')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='apellido_materno')),
                ('direccion', models.CharField(max_length=200, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=15, verbose_name='telefono')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('compra', models.PositiveIntegerField(verbose_name='compra')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
            ],
        ),
    ]
