# Generated by Django 4.2.5 on 2023-11-07 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstado', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(default=0.00031456432840515884, on_delete=django.db.models.deletion.CASCADE, to='producto.estado', verbose_name='estado'),
            preserve_default=False,
        ),
    ]
