# Generated by Django 4.2.5 on 2023-11-26 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_estado_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dni',
            field=models.CharField(max_length=8, verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='producto.CarritoProducto', to='producto.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='carrito',
            field=models.OneToOneField(default=0.0011683817912191616, on_delete=django.db.models.deletion.CASCADE, to='producto.carrito', verbose_name='carrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.descuento', verbose_name='Descuento'),
        ),
    ]
