# Generated by Django 4.2.5 on 2023-12-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante',
            field=models.ImageField(null=True, upload_to='pagos/', verbose_name='Comprobante'),
        ),
    ]
