# Generated by Django 4.2.5 on 2023-12-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0012_pedido_comprobante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoproducto',
            old_name='producto',
            new_name='CarrProd',
        ),
        migrations.RenameField(
            model_name='carritoproducto',
            old_name='carrito',
            new_name='carritoP',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='price',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombreEstado',
            field=models.CharField(max_length=100, verbose_name='nombreEstado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprobante',
            field=models.ImageField(null=True, upload_to='comprobantes/', verbose_name='Comprobante'),
        ),
    ]
