# Generated by Django 4.2.5 on 2023-12-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0013_rename_producto_carritoproducto_carrprod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoproducto',
            old_name='carritoP',
            new_name='carrito',
        ),
        migrations.RenameField(
            model_name='carritoproducto',
            old_name='CarrProd',
            new_name='producto',
        ),
    ]
