# Generated by Django 4.2.5 on 2023-12-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_rename_carritop_carritoproducto_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.categoria', verbose_name='Categória'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.talla', verbose_name='Talla'),
        ),
    ]
