# Generated by Django 4.2.5 on 2023-12-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0015_alter_producto_categoria_alter_producto_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='producto.carrito', verbose_name='carrito'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='producto.estado', verbose_name='estado'),
        ),
    ]
